/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_auth;

import java.io.IOException;

import org.json.JSONObject;

import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Base64;
import java.util.Map;

import java.time.LocalDateTime;
import java.text.SimpleDateFormat;

import java.security.Key;
import java.security.KeyFactory;
import java.security.GeneralSecurityException;
import java.security.spec.X509EncodedKeySpec;
import java.security.spec.ECPrivateKeySpec;

public class App {

    public static Key loadPublicKey(String stored) throws GeneralSecurityException, IOException 
    {
        byte[] data = Base64.getDecoder().decode((stored.getBytes()));
        X509EncodedKeySpec spec = new X509EncodedKeySpec(data);
        KeyFactory fact = KeyFactory.getInstance("EC");
        return fact.generatePublic(spec);

    }

    public static String generateHeader(String stringToSign, String apiKey)
    {

        String token = null;

        try {
            JwtGenerator generator = new JwtGenerator();

            Map<String, String> claims = new HashMap<>();
            
            claims.put("sub", apiKey);
            claims.put("signature", stringToSign);

            token = generator.generateJwt(claims);

            String authorization = "QIT" + apiKey + ":" + token;

            String request_header = new JSONObject()
                    .put("AUTHORIZATION", authorization)
                    .put("API-CLIENT-KEY", apiKey)
                    .toString();

            System.out.println(request_header);
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            return token;
        }

    }

    public static void main(String[] args) throws GeneralSecurityException, IOException 
    {

        String clientPrivateKey = "MIHcAgEBBEIBell7txNDr4xYXlDeUO4ySCNRlguHisiC5nUgWDS96j4K2wPksMSA"
        + "C6RNmzaz58GPcirbCTHRkpHWhoEaTXO/U4KgBwYFK4EEACOhgYkDgYYABADijSa1"
        + "pf3o4QHKevPQ3dEcPqLQLu76K8m0fWo4dYQsaEUou8PbVlvuuMJZyuFbUPSGl+Rz"
        + "4DVE3DV1SXrCybyKYgDz2/DKYDLd8aE0YjSfQxkWmOj2Eyvktk3Yk0s/seR4ZhmH"
        + "eUhPie2ob0d7QIsC47bqnlAKllL6hPCD7QNZmt1npQ==";

        String apiKey = "97ad0301-869c-4481-98b6-294b139e09ae";
        
        String qiPublicKey = "MIGbMBAGByqGSM49AgEGBSuBBAAjA4GGAAQBrhSkDcGyG1u3G47sfe5HW8Wx8egS"
        + "2ULxWgZ3aUAIG9p0+G+A7CNpZsrElTC9WQ4BoOFQZQgpqh+uj/Nf9yE14/EBUDoM"
        + "hhIek47tcCGBcbHCWsngMv0bSEfw+KRj3deWzopbI5xHj6DJZi5TrgFxF+3/GKMR"
        + "7aeiPBNb0lb0rfdNO5Q=";

        String qiAuthAddress = "https://api-auth.sandbox.qitech.app";

        Key publicKey = loadPublicKey(qiPublicKey);

        String endpoint = "/test/" + apiKey;
        String method = "GET";
        String contentType = "application/json";

        String md5Body = "";
        String requestBody = null;

        Date now = new Date();  

        String date = new SimpleDateFormat​("E, dd MM yyyy H:m:s", Locale.US).format(now);
        String final_date = date + " GMT";
      
        String stringToSign = method + "\n" + md5Body + "\n" + contentType + "\n" + final_date + "\n" + endpoint;
      
        generateHeader(stringToSign, apiKey);

    }
}
